ipfs-force-community/droplet

models/badger/retrieval_deal.go
models/badger/storage_deal.go

use new travel version instead of old.

refactor travel function

---

api/clients/modules.go
config/config.go
config/def_config.go

1. fix: set default auth node url to empty.
2. fix: panic on startting undependent.

fix: panic on startting undependent

---

api/clients/mix_msgclient.go
api/clients/modules.go

set DI of MpoolReplaceParams.Venusmessager optional instead of building a nil.

set DI of MpoolReplaceParams.Venusmessager optional

---

client/client.go
client/types.go
cmd/market-client/retrieval.go

new command for client query retrival ask

new command for client query retrival ask

---

client/modules.go
network/modules.go
network/network.go

can't start market client for Dependency/inject missing type providers

fix:Dependency/inject missing type providers

---

api/impl/venus_market.go
retrievalprovider/provider.go

1. add implementation of IRerivealProvider signature check.
2. fix lost 'ctx' params in IRerivealProvider method.

fix: IRerivealProvider method signature

---

piecestorage/client_s3.go
piecestorage/s3.go

1. s3.GetReadUrl will check if object exists.
2. s3Client.ReadObject check response status code.

fix: s3: more checks on s3 data transfer

---

cmd/market-client/data.go
storageprovider/storageprovider.go

1. fix: not set piece status on importing offline deal.
2. feat: print piece byte size.

Fix: offline deal: not set piece status

---

cmd/venus-market/pool-run.go
rpc/piece_storage_server.go

- register resource router correctly
- output http error msg & code correctly
- close obj reader after request done

fix: make resource service work

---

storageprovider/deal_assign_util.go
storageprovider/deal_assign_util_test.go
storageprovider/deal_assigner.go

fix: assign deals and align with pledge pieces

---

api/impl/market_event.go
api/impl/venus_market.go
cli/actor.go
cli/market.go
go.mod
go.sum
models/badger/storage_deal.go
models/mysql/storage_deal.go
models/repo/repo.go
storageprovider/deal_assign_util.go
storageprovider/deal_assign_util_test.go
storageprovider/deal_assigner.go
storageprovider/deal_tracker.go

New features:
for managing miner deal proposals in a easier approach,
1. storage-deals list show piece status for each deal.
```shell
./venus-market storage-deals list --miner f01043
/root/.venusmarket
ProposalCid  DealId  State                 PieceState  Client                                     Provider  Size    Price                     Duration
...f4f65jpa  2927    StorageDealActive     Assigned    t16qnfduxzpneb2m3rbdasvhgk7rmmo32zpiypkaq  t01043    512B    0.000002491087609449 FIL  522419
```
2. stroage-deals update command add flag to set piecestate:
```shell
./venus-market storage-deals update
NAME:
venus-market storage-deals update - update deal status
USAGE:
venus-market storage-deals update [command options] [arguments...]
OPTIONS:
--proposalcid value
--really-do-it …
```

feat: cmd line tool: list/update miner deal state

---

models/mysql/storage_deal.go

fix update deal status on mysql not working

fix: update deal status on mysql not working

---

go.mod
go.sum
rpc/rpc.go

upgrade venus-auth, remove log param for construction of AuthMux

rename auth log to "auth_client"

---

cmd/market-client/retrieval.go
models/badger/db.go
models/badger/storage_ask.go
models/module.go
models/mysql/db.go
models/repo/repo.go
models/testing.go
retrievalprovider/piecestore.go
retrievalprovider/requestvalidation.go
retrievalprovider/stream_handler.go

- feat uniform `recode not found` error
- fix market-client retrieval-ask error on index not exists.
Fixes https://github.com/filecoin-project/venus/issues/4893

feat : uniform not found error in data retrieval

---

storageprovider/deal_tracker.go

fix: placeholder in output log format string

---

.github/workflows/tag-workflow.yml
.gitignore
Makefile
config/config.go
dagstore/wrapper.go
docker/config/PieceStorage.toml
docker/script/compose.sh
docker/script/init.sh
docker/script/wait-for-it.sh
dockerfile
paychmgr/manager.go
paychmgr/mock_test.go
paychmgr/paychget_test.go
paychmgr/simple.go
retrievalprovider/datatransfer_handler.go
storageprovider/deal_tracker.go

merge v2.0.1 into perp/v2.2.0-rc2.

chore: merge v2.0.1 into perp/v2.2.0-rc2

---

Makefile
dockerfile

change to build docker image from local repo rather than from git chech out

fix: venus-market : change to  build docker image from local repo 

---

minermgr/minermgr.go
storageprovider/storageprovider_test.go

fixes https://github.com/filecoin-project/venus/issues/4944
修复miner的`owner`为multi-sig地址时, 无法启动的问题.

fix: if a owner is multi-sig address

---

dockerfile

fix https://github.com/filecoin-project/venus/issues/4999
update dependencies to ddl

fix #4999 : venus-market : update dependencies of ddl

---

docker/config/PieceStorage.toml

fix https://github.com/filecoin-project/venus/issues/5034
update docker config  clip with change from valid config

chore: update docker config  clip with change from valid config 

---

.github/workflows/go.yml
.github/workflows/tag-workflow.yml

1. git-based checking of repository changes
2. go mod tidy checks
would resolve https://github.com/filecoin-project/venus/issues/5074

feat: git action: apply go mode tidy checks on PRs

---

cmd/market-client/storage.go
models/module.go

resolve https://github.com/filecoin-project/venus/issues/4881
as described in title

feat: cli : add dataCID when client deal list

---

cmd/venus-market/main.go

fix filecoin-project/venus#5022

fix：可以配置重复的StorageMiners

---

.github/workflows/tag-workflow.yml

only trigger auto publish on PR is merged
原因及方案说明: https://github.com/filecoin-project/venus/issues/5090

chore: git action: only trigger auto publish on PR merged

---

.github/workflows/tag-workflow.yml

fix: git-action: mission colon in auto release workflow

fix: git-action: mission colon in auto release workflow

---

README.md
docs/zh/market-client配置解释.md
docs/zh/venus-market配置解释.md
docs/zh/快速上手.md
docs/zh/快速启用.md

resolve https://github.com/filecoin-project/venus/issues/5055
As described in tietle

docs: add config explain and quick start 

---

api/impl/venus_market.go
cli/market.go
go.mod
go.sum
storageprovider/storageprovider.go
storageprovider_tesst/storage_ask_test.go
storageprovider_tesst/storageprovider_test.go
storageprovider_tesst/testdata/import_deal.json

close https://github.com/filecoin-project/venus/issues/5088
As decribed in title

feat: 增加导入离线订单的接口和命令 / add interface and cli import offline deal 

---

docs/zh/如何迁移离线订单.md

involve  https://github.com/filecoin-project/venus/issues/5088
As described in title.

doc : 增加导入离线订单的文档 / add description how to import offline deal in Chinese

---

api/impl/venus_market.go
cli/piece-storage.go
config/config.go
docs/zh/venus-market配置解释.md
go.mod
go.sum
piecestorage/s3.go
piecestorage/s3_test.go
piecestorage/storagemgr.go

close https://github.com/filecoin-project/venus/issues/5069
add bucket config in piecestorage
fix the interface to add S3 piecestorage
change the way to explain config about S3 piecestorage

feat: 在对象存储的piecestorage增加bucket配置项 / add bucket config in piecestorage

---

docs/zh/快速启用.md

docs: fix typos

---

cmd/market-client/data.go

close https://github.com/filecoin-project/venus/issues/5224

feat: make byte count in output of commP  obvious

---

cmd/market-client/data.go
go.mod
go.sum
models/badger/fund.go
models/badger/paych.go
models/badger/retrieval_ask.go
models/badger/retrieval_deal.go
models/badger/storage_deal.go
models/badger/utils.go
models/mysql/cid_info.go
models/mysql/db.go
models/mysql/fund.go
models/mysql/paych.go
models/mysql/retrieval_ask.go
models/mysql/retrieval_deal.go
models/mysql/retrieval_deal_test.go
models/mysql/storage_deal.go
models/repo/repo.go
models/storage_deal_test.go
paychmgr/paych_test.go
paychmgr/state.go

close https://github.com/filecoin-project/venus/issues/5179
depends on pre-task: https://github.com/filecoin-project/venus/pull/5248
fix: Everytime mysqlStorageRepo.SaveDeal is called, the `create_at` of corresponding `deal` is update to  0.
原始代码直接db.Save()的逻辑为先尝试`Update`失败后, 再`Create`, 在update时会直接将`create_at`更新为0,
修改为使用下面的方式来执行`upsert`
```go
db.Clauses(clause.OnConflict{}).Create(fromStorageDeal(storageDeal))
```
因为在`gorm`中, 为`OnConflict`更新时, 会自动识别`CreateAt`字段并忽略此字段的更新.
如下:
https://github.com/go-gorm/gorm/blob/8c3018b96aea241a35b769291de6edd2a3378b44/callbacks/create.go#L296-L324

fix:Everytime call mysqlStorageRepo.SaveDeal `create_at` was update to 0

---

Makefile

involve https://github.com/filecoin-project/venus/issues/5267
- make deps before make docker

fix: make deps before make docker

---

tools/import-deal/main.go
tools/import-deal/types/types.go

fix: Prepared statement contains too many placeholders

---

models/badger/db.go
models/badger/paych.go
models/badger/testing.go
models/module.go
models/paych_test.go
paychmgr/testing.go

https://github.com/filecoin-project/venus-market/pull/208 后续
继解耦`paychrepo`为`paychInfoRepo`和`paychMsgRepo`后, 将这两个类型用依赖注入的方式来创建.

refactor: inject paychInfoRepo and paychMsgRepo

---

version/version.go

close nil
1. 升级ffi
2. 版本号改为`v2.4.0-rc2`

Feat/upgrade ffi && change build version to v2.2.0-rc2

---

storageprovider/dealpublisher.go

close filecoin-project/venus#5335

feat: dealpublisher: check for duplicate deals before adding

---

go.mod
storageprovider/ondealsectorcommitted.go

close filecoin-project/venus#5342

feat: storageprovider: opt markets event handler

---

tools/import-deal/types/types.go

fix: use unpad size for payload size

---

storageprovider/deal_tracker.go

fix: correct precommit msg check

---

api/impl/venus_market.go
retrievalprovider/piecestore.go
retrievalprovider/revalidator.go

fix: skip not found error

---

tools/import-deal/types/types.go

opt(tools): Orders that are not allocated deals

---

models/mysql/db.go
models/mysql/fund.go
models/mysql/paych.go
models/mysql/retrieval_ask.go
models/mysql/retrieval_ask_test.go
models/mysql/retrieval_deal.go
models/mysql/storage_ask.go
models/mysql/storage_deal.go

https://github.com/filecoin-project/venus/issues/5344
`direction` `next_lane`
`payment_interval` `payment_interval_increase`
`store_id` `status` `total_sent` `current_interval` 
`cdp_proposal_id` `cdp_payment_interval` `cdp_payment_interval_increase` `cdp_unseal_price`
`min_piece_size` `max_piece_size` `timestamp` `expiry` `seq_no`
`state` `payload_size` `slash_epoch` `deal_id` 
`creation_time` `sector_number` `offset` `length`
`cdp_piece_size` `cdp_start_epoch` `cdp_end_epoch` `cdp_unseal_price`
`tci_channel_id` `ref_piece_size` `ref_raw_block_size`
`amt_reserved`
`amount` `pending_amount` `available_amount` `pending_available_amount`
`price_per_byte` `unseal_price`
`funds_received` `cdp_unseal_price` `cdp_price_perbyte`
`price` `verified_price`
`funds_reserved` …

chore: set the default 0 for big.Int

---

cli/piece-storage.go
cli/tablewriter/tablewiter_test.go
cli/tablewriter/tablewriter.go

close https://github.com/filecoin-project/venus/issues/5502

fix: fix output of list piecestorage / 修复列出 piecestorage 时出现的乱序问题

---

api/impl/venus_market.go
storageprovider/datatransfersubscriber.go
storageprovider/deal_handler.go
storageprovider/deal_tracker.go
storageprovider/modules.go
storageprovider/storage_provider.go
storageprovider/storageprovider_test.go
storageprovider/stream.go

close https://github.com/filecoin-project/venus/issues/5493

Feat/tanlang/fix provider event / 修复 StorageProvider 的事件机制

---

docs/zh/metric指标解释.md
metrics/metrics.go

https://github.com/filecoin-project/venus/issues/5488

chore: add jsonrpc metrics

---

.golangci.yml
cmd/market-client/client_retr.go

close https://github.com/filecoin-project/venus/issues/5355

chore: Add retrieval deal ID and bytes transferred to retrieval output

---

cmd/venus-market/main.go
cmd/venus-market/run.go
config/def_config.go
docs/zh/venus-market配置解释.md
docs/zh/快速启用.md

feat: Use lotusnode correctly as market service

---

config/common.go
config/def_config.go
retrievalprovider/provider.go
retrievalprovider/requestvalidation.go
retrievalprovider/stream_handler.go

fix: fix retrieval payment address config

---

config/common.go
go.mod
go.sum
rpc/rpc.go

close https://github.com/filecoin-project/venus/issues/5570

feat: save api secret, not change token when reboot

---

storageprovider/ondealsectorcommitted.go

Chore: backport: #261

---

config/config.go
config/def_config.go
docs/zh/venus-market配置解释.md
docs/zh/快速启用.md

opt: Avoid configuration file generating miners = []

---

dealfilter/cli.go

close https://github.com/filecoin-project/venus/issues/5565

feat: integrate CIDgravity

---

cmd/market-client/storage.go

https://github.com/filecoin-project/lotus/pull/10101

fix: cli: Wait for all results in GetAsks

---

cli/storage-cfg.go

close https://github.com/filecoin-project/venus/issues/5701

feat: add error notice for no specific flags

---

minermgr/miner_mgr.go

fix: Correct constructing slices of MinerList API

---

version/version.go

chore: bump version to 2.5.1

---

minermgr/miner_mgr.go

fix: cherry-pick #279

---

cmd/market-client/main.go
cmd/venus-market/main.go
cmd/venus-market/run.go
go.mod
go.sum
rpc/rpc.go

feat: add status api to detect api ready

---

docs/en/market-client-configurations.md
docs/zh/market-client配置解释.md

close https://github.com/filecoin-project/venus/issues/5811

docs: add en client config docs

---

docs/zh/订单过滤器.md

close https://github.com/filecoin-project/venus/issues/5835

docs: add document about deal filter

---

api/impl/venus_market.go
cli/retrieval-deals.go
cli/storage-deals.go
go.mod
go.sum
models/badger/retrieval_deal.go
models/badger/retrieval_deal_test.go
models/badger/storage_deal.go
models/badger/storage_deal_test.go
models/migrate_test.go
models/mysql/retrieval_deal.go
models/mysql/retrieval_deal_test.go
models/mysql/storage_deal.go
models/mysql/storage_deal_test.go
models/repo/repo.go
models/storage_deal_test.go
retrievalprovider/provider.go
storageprovider/storage_provider.go

close https://github.com/filecoin-project/venus/issues/5767

feat: opt deal list cmds

---

cli/data_transfer.go

close https://github.com/filecoin-project/venus/issues/5766

feat: add command to cancel data transfer

---

storageprovider/deal_assigner.go

fix(ReleaseDeals): check deal state

---

retrievalprovider/provider.go

close https://github.com/filecoin-project/venus/issues/5851
querytimeout从5s改成5minutes

feat: more time for query retrieval ask

---

cmd/market-client/datacap.go
cmd/market-client/main.go
docs/zh/datacap续期.md

close https://github.com/filecoin-project/venus/issues/5759

feat: add command to expend claim term

---

CHANGELOG.md
version/version.go

chore: bump version to v2.6.1

---

storageprovider/deal_handler.go

close https://github.com/filecoin-project/venus/issues/5944

opt: not wait for index results to be generated

---

CHANGELOG.md
storageprovider/deal_handler.go
version/version.go

Chore/bump v2.7.2

---

dealfilter/cli.go
docs/zh/订单过滤器.md
storageprovider/deal_handler.go

close https://github.com/filecoin-project/venus/issues/5834
ref https://github.com/filecoin-project/venus/issues/5669
- 修改了 dealfiter 传出的数据结构
- 当订单被拒绝时, 输出日志

fix: adapt deal filter format to CIDgravity / 修改 dealfilter 的实现, 以兼容 CIDgravity 

---

CHANGELOG.md
version/version.go

chore: bump version to v2.7.3

---

README.md

doc: fix link

---

retrievalprovider/httpretrieval/server.go

chore: output piece size to log

---

go.mod
go.sum

feat: update gateway deps

---

retrievalprovider/httpretrieval/server.go

fix https://github.com/ipfs-force-community/droplet/pull/338

fix: close reader

---

cli/storage-deals.go
cli/testdata/lotus_miner_query_result.json
cli/util_test.go
storageprovider/storage_provider.go

close https://github.com/ipfs-force-community/droplet/issues/367

fix: import deals slow

---

cli/storage-deals.go
cli/util.go

fix: https://github.com/ipfs-force-community/droplet/pull/335

fix: import boost deal

---

CHANGELOG.md
version/version.go

chore: bump up version to v2.8.1

---

retrievalprovider/httpretrieval/server.go

chore: output average write to log

---

cmd/droplet/run.go
models/auth.go
retrievalprovider/event_stream.go

close https://github.com/ipfs-force-community/droplet/issues/395

feat: add IAuthClient stub

---

api/impl/venus_market.go
go.mod
go.sum
storageprovider/deal_assign_util.go
storageprovider/deal_assign_util_test.go
storageprovider/deal_assigner.go

ref #404
Cherry-pick #404 to release/v2.8

Cherry pick #404 to release v2.8

---

cli/storage-deals.go
cli/testdata/lotus_miner_query_result.json
cli/util.go
cli/util_test.go
storageprovider/storage_provider.go

cherry pick 371

---

cli/storage-deals.go

修复导入 slashed 订单时，PieceStatus 不对 

fix: handle slashed deal

---

CHANGELOG.md
version/version.go

chore: release v2.8.2

---

cmd/droplet-client/datacap.go

fix: parse address failed

---

storageprovider/deal_handler.go

close https://github.com/ipfs-force-community/droplet/issues/410

feat: Automatically delete temporary car files

---

CHANGELOG.md
Makefile
go.mod
go.sum
version/version.go

chore: bump version to v2.9.0-rc1

---

api/clients/modules.go
api/clients/node_client.go
cmd/droplet-client/main.go
cmd/droplet/run.go
config/config.go
config/modules.go

close https://github.com/ipfs-force-community/droplet/issues/423

fix: do not cover token of node, auth, messager  

---

docs/zh/droplet配置解释.md
docs/zh/快速启用.md

doc: update doc about unit entry

---

config/modules.go
dagstore/wrapper.go
models/badger/storage_deal.go
models/mysql/storage_deal.go
models/mysql/storage_deal_test.go

close
1. 一个piece发了两次，第一次失败了，第二次成功了，生成索引的时候是按piececid来查找piece信息，会找到第一次发的订单，所以有些信息找不到导致生成索引失败了
2. 增加对 MongoDB URL 的检查
3. 修复 droplet-client 启动失败

fix: payload size is 0 when generate index

---

cli/storage-deals.go
cli/util.go
cmd/droplet-client/storage.go
cmd/droplet-client/storage_v2.go
storageprovider/deal_handler.go
storageprovider/storage_provider.go
storageprovider/stream.go

https://github.com/ipfs-force-community/droplet/issues/421

feat: support deal status protocol

---

cli/storage-deals.go
go.mod
go.sum
models/badger/storage_deal.go
models/mysql/storage_deal.go
models/mysql/storage_deal_test.go

close https://github.com/ipfs-force-community/droplet/issues/439

feat: list deal descending by default

---

storageprovider/deal_assigner.go

fix(release deals): skip update state if deal expired

---

CHANGELOG.md
storageprovider/deal_assigner.go
version/version.go

close
- cherry pick #443 to release/v2.8
- release v2.8.3

Cherry pick #443 to release v2.8

---

cmd/droplet-client/pieceinfo.go

https://github.com/ipfs-force-community/droplet/pull/431

fix: generate manifest

---

CHANGELOG.md
version/version.go

chore: bump version to v2.9.1

---

cmd/droplet-client/retrieval.go
cmd/droplet-client/storage.go

close https://github.com/ipfs-force-community/droplet/issues/433

fix: add timeout for query ask

---

dagstore/wrapper.go

close https://github.com/ipfs-force-community/droplet/issues/452

fix: Do not recover failed indexes on startup

---

docs/zh/订单过滤器.md

add filter Example

---

storageprovider/stream.go

close https://github.com/ipfs-force-community/droplet/issues/456

fix: could not judge offline deal from boost

---

storageprovider/deal_handler.go

fix: check deal end epoch with DealMaxDuration

---

go.mod
go.sum

chore: update go-jsonrpc v0.1.8

---

CHANGELOG.md
version/version.go

chore: bump version to v2.10.0-rc2

---

cli/storage-deals.go
storageprovider/stream.go

fix: use the received deal uuid

---

cli/retrieval-deals.go
retrievalprovider/provider_datatransfer_sub.go

close https://github.com/ipfs-force-community/droplet/issues/476
1. 更新订单状态
2. 关闭 blockstore

fix: clean blockstore after retrieval completed

---

CHANGELOG.md
version/version.go

chore: bump version to v2.10.0-rc3

---

cli/util.go
cli/util_test.go

fix: set deal id when import deal from boost

---

api/impl/venus_market.go
cli/storage-deals.go
cli/util.go
cli/util_test.go
go.mod
go.sum
storageprovider/storage_provider.go

chore: pick 471 480

---

CHANGELOG.md
go.mod
go.sum
version/version.go

chore: bump version to v2.10.0-rc4

---

CHANGELOG.md
go.mod
go.sum
retrievalprovider/provider_datatransfer_sub.go
version/version.go

chore: bump version to v2.10.0-rc5

---

CHANGELOG.md
go.mod
go.sum
retrievalprovider/httpretrieval/server.go
version/version.go

chore: bump version to v2.10.0-rc6

---

piecestorage/filestore.go
piecestorage/store_wrapper.go

feat: add regular file check

---

config/config.go

fix: disable auth when off chain service

---

.github/workflows/build_upload.yml

close https://github.com/ipfs-force-community/droplet/issues/488

opt: split into droplet and droplet-client

---

cli/storage-deals.go
config/config.go
models/badger/storage_deal.go
models/mysql/storage_deal.go
piecestorage/filestore.go
piecestorage/filestore_test.go
piecestorage/store_wrapper.go

Chore/pick 492 493 495 497 500 501 to v2.10

---

version/version.go

chore: bump up version to v2.10.1

---

CHANGELOG.md
version/version.go

chore: bump version to v2.11.0-rc1

---

cli/direct-deal.go
dagstore/market_api.go
models/badger/direct_deal.go
models/badger/direct_deal_test.go
models/badger/storage_deal.go
models/badger/testing.go
models/mysql/direct_deal.go
models/mysql/direct_deal_test.go
models/repo/repo.go
storageprovider/direct_deal_provider.go

fix: generate direct deal index

---

cli/direct-deal.go
cmd/droplet-client/direct-deal.go
docs/zh/direct-on-boarding.md

feat: auto import direct deal

---

storageprovider/deal_assign_util.go
storageprovider/deal_assigner.go

opt: add assign log

---

storageprovider/deal_handler.go
storageprovider/direct_deal_provider.go
storageprovider/storage_provider.go

chore: output payload size to log

---

api/impl/venus_market.go
cli/storage-deals.go
cli/util.go
go.mod
go.sum
piecestorage/filestore.go
piecestorage/filestore_test.go
piecestorage/storagemgr_test.go
piecestorage/store_wrapper.go

fix: Incorrect payload size

---

CHANGELOG.md
version/version.go

chore: bump version v2.11.1

---

piecestorage/filestore.go
piecestorage/filestore_test.go
piecestorage/store_wrapper.go

fix: import slow

---

piecestorage/store_wrapper.go
retrievalprovider/httpretrieval/server.go
retrievalprovider/httpretrieval/server_test.go

fix: divide by zero

---

cmd/droplet-client/direct-deal.go
cmd/droplet-client/util.go

提供的 piece size 已经是 padded 后的，增加一个flag `piece-size-padded`，跳过 padded

fix: piece size already padded

---

cmd/droplet-client/storage.go
cmd/droplet-client/storage_v2.go
docs/zh/drople-client发布v2订单.md

feat: send deal to boost

---

storageprovider/deal_assign_util.go

fix: Do not check the startepoch and endepoch of direct deal

---

cli/direct-deal.go
docs/zh/direct-on-boarding.md

feat: import deal by message

---

api/impl/venus_market.go
config/config.go
config/def_config.go
dagstore/wrapper.go
dagstore/wrapper_test.go
go.mod
go.sum
retrievalprovider/httpretrieval/bswrap.go
retrievalprovider/httpretrieval/server.go
retrievalprovider/httpretrieval/trustless_handler.go
storageprovider/deal_tracker.go
storageprovider/direct_deal_provider.go
storageprovider/storage_provider.go

fix: Increase the inspection interval time

---

.golangci.yml
cli/pieces.go
cli/retrieval-asks.go
cli/stats.go
cli/storage-ask.go
cli/util.go
cmd/droplet-client/datacap.go
cmd/droplet-client/paych.go
cmd/droplet-client/storage.go

chore: fix lint

---

cli/direct-deal.go
cmd/droplet-client/direct-deal.go

opt: update ddo deal default start epoch to 30 days
