cli/util.go, cmd/market-client/main.go, cmd/venus-market/main.go
fix:market-client api namespace on the server side inconsistent with client side.
this causes following error:
```shell
2021-12-08T17:07:18.185+0800	ERROR	rpc	go-jsonrpc@v0.1.4-0.20210721095535-a67dff16de21/server.go:103	RPC Error: method 'VENUS_MARKET.ClientListImports' not found
```
=> fix:market-client api namespace inconsistent

.github/workflows/tag-workflow.yml
clean go mod cache before make
=> clean go mod cache before make

cmd/market-client/storage.go
Doesn't clear older illegal addresses in deal initialization with interactive mode.
Fixes filecoin-project/venus#4879
=> fix: Doesn't clear older illegal addresses in deal initialization with interactive mode.

client/client.go, cmd/market-client/client_retr.go
1. `market-client retrieval retrieve` can't exit automatically if provider canceled the retrieval.
if provider canceled the `retrieval`, the client would receive a `StateCancelled` state, but we haven't handle it.
2. the `event` in `market-client retrieval` outputs always be an incorrect '**New**'. as following:
```shell
./market-client retrieval retrieve --provider f01192 --maxPrice 1fil bafk2bzacebbko4p5smouvkzcrcfw7rtapm5h6srptevkpdqzgh3ql47pfcbha ./r_data/bafk2bzacebbko4p5smouvkzcrcfw7rtapm5h6srptevkpdqzgh3ql47pfcbha
Recv 0 B, Paid 0 FIL, New (New), 0s
Recv 0 B, Paid 0 FIL, New (WaitForAcceptance), 2ms
Recv 0 B, Paid 0 FIL, New (Accepted), 16ms
Recv 0 B, Paid 0 FIL, New (PaymentChannelCreating), 43ms
Recv 2.864 KiB, Paid 0 FIL, New (PaymentChannelCreating), 1m25.97s
Recv 2.864 KiB, …
```
=> fix handle provider canncel state

models/badger/paych.go, paychmgr/manager.go, paychmgr/paych.go, paychmgr/simple.go
没有以正确的方式检测 ChannelNotFound错误, 导致数据检索失败的问题.
在`paychanrepo`的mysql实现中, 如代码所示:
https://github.com/filecoin-project/venus-market/blob/4d8533af0138c2d003dade56ced721ae1eac1b23/models/mysql/paych.go#L128-L136
如果channel不存在, 返回的错误是: `repo.ErrNotFound`
但在`PayChManager`中, 却通过判断err是否等于`types.ErrChannelNotFound`来判断channel是否存在, 此错误最终会导致数据检索失败.
https://github.com/filecoin-project/venus-market/blob/4d8533af0138c2d003dade56ced721ae1eac1b23/paychmgr/manager.go#L312-L321
=> fix: detect ChannelNotFound error with correct approach

retrievalprovider/datatransfer_handler.go
Since `GetDeal` returns an error, 
https://github.com/filecoin-project/venus-market/blob/4d8533af0138c2d003dade56ced721ae1eac1b23/retrievalprovider/datatransfer_handler.go#L42-L50
The first returned param `deal` would be nil,  
Should not use it again, just returns the error is ok.
=> fix, null pointer exception in data-transfer-handler

cmd/venus-market/main.go, cmd/venus-market/pool-run.go, cmd/venus-market/solo-run.go, storageprovider/client.go, storageprovider/currentdealinfo.go, storageprovider/provider.go
loadActorsWithCmdBefore函数中, 会解析`MarketConfig`, **同时**在`pool/solo run`中也会解析`MarketConfig`
为了提高代码重用度和可维护性, 采用下面的方式进行重构:
=> refactor: load v8 actors before solo/pool run

api/clients/modules.go
此配置项用于创建定时器, 定时检查过期的请求. 
在venus-gateway中, 没有对此值的有效性进行判断, 如果不设置将最终导致程序panic.
https://github.com/ipfs-force-community/venus-gateway/blob/45c7c99119e76f492b8f011f85834684c53e842c/types/base_event.go#L123-L125
https://github.com/ipfs-force-community/venus-gateway/pull/53
=> Fix: crush caused by creation 0 interval timer

paychmgr/manager.go, paychmgr/mock_test.go, paychmgr/paychget_test.go, paychmgr/simple.go
**TestPaychGetRestartAfterAddFundsMsg测试中, 可能会陷入永远等待一个不会被触发的channel接收中, 最终导致检查`timeout`失败.**
1. 代码`GetPaych`, 会触发非常多的异步代码:
https://github.com/filecoin-project/venus-market/blob/25483cb968588248e12867f934ea1db27f66ea81/paychmgr/paychget_test.go#L454-L457
2. 但最终, 会触发`AddFunds`,并通过`response`管道, 等待消息在链上的`receipt`:
https://github.com/filecoin-project/venus-market/blob/25483cb968588248e12867f934ea1db27f66ea81/paychmgr/mock_test.go#L154-L158
3. 当我们通过`mockapi.close`, 来关闭时, 
https://github.com/filecoin-project/venus-market/blob/25483cb968588248e12867f934ea1db27f66ea81/paychmgr/mock_test.go#L181-L193
第2步中的, 管道会收到正确的`receipt`.
4. 在`channelAccessor.waitAddFundsMsg`中, 会认为消息执行并上链. 最终将`channel.AddFundsMsg`设置为nil, 并更新到repo中.
https://github.com/filecoin-project/venus-market/blob/25483cb968588248e12867f934ea …
=> fix: TestPaychGetRestartAfterAddFundsMsg may stuck in forever waiting

retrievalprovider/datatransfer_handler.go
fix: 当检索订单状态为`rm.DealStatusFundsNeededUnseal`时, 
接收到`rm.ProviderEventDealAccepted`事件后, 就直接`UnsealData` 直接开始数据传输, 
最终导致检索服务和客户端的状态混乱订单失败的问题.
fixes: https://github.com/filecoin-project/venus/issues/4908
=> fix : retrieval market: retrieval provider begins data transfer  in incorrect state.

api/clients/sign_client.go, cmd/venus-market/main.go, cmd/venus-market/pool-run.go, cmd/venus-market/solo-run.go, config/config.go
fix: 创建了错误的signer类型, 导致签名失败的问题.
=> Fix: create incorrect signer type

dagstore/mock_dagstore_wrapper.go, models/badger/storage_deal.go, models/mysql/storage_deal.go, models/repo/repo.go, retrievalprovider/piecestore.go, retrievalprovider/piecestore_test.go
resolve: https://github.com/filecoin-project/venus/issues/4970
=> feat:support get deals by datacid from database but not only rely on topindex

go.mod, go.sum, storageprovider/deal_assign_util.go, storageprovider/deal_assign_util_test.go
是 filecoin-project/venus#4958 的子任务，且应当先完成  filecoin-project/venus#5043
=> 支持按照生命周期过滤分配订单

client/client.go
close https://github.com/filecoin-project/venus/issues/4908
The approach of computing `price per byte` in retrieval client is incorrect, 
with this approach:
https://github.com/filecoin-project/venus-market/blob/ab7c180f5a65a1c7ab549cfca78463f2a9329fbc/client/client.go#L803
if `order.UnsealPrice` is not 0,  this causes `price per byte`(ppb) larger than it's actual amount..
this would finally cause `retrieval deal` failed with `ClientEventVoucherShortfall`
following is the Fragment  of this issue:
```
Recv 30.01 MiB, Paid 0.0000001 FIL, VoucherShortfall (CheckFunds), 1m48.883s
Recv 30.01 MiB, Paid 0.0000001 FIL, FundsExpended (InsufficientFunds), 1m49.065s
```
=> fix: incorrect computing price-per-bytes in retrieval client

api/clients/gateway_client.go, api/clients/modules.go, api/clients/sign_client.go, api/impl/market_event.go, cmd/venus-market/pool-run.go, cmd/venus-market/solo-run.go, fundmgr/fundmanager_test.go, go.mod, go.sum, minermgr/minermgr.go, network/transport.go, rpc/auth.go, rpc/rpc.go, storageprovider/deal_tracker.go
close filecoin-project/venus/issues/5210
one of sub tasks of  filecoin-project/venus/issues/4894
The latest `venus-gateway` removed some local defined interfaces which was replaced by interfaces defined in`venus-shared`, 
Upgrade `veus-gateway`, and suit those changes.
=> chore: upgrade gateway go mod

cmd/market-client/client_retr.go, cmd/market-client/storage.go, network/transport.go
close
fix: help string in cli.
=> fix: command help string

api/impl/venus_market.go, go.mod, go.sum, models/badger/retrieval_ask.go, models/badger/storage_ask.go, models/mysql/storage_ask.go, models/repo/repo.go, models/storage_ask_test.go, storageprovider/storage_ask.go, storageprovider/stream.go
close
在venus-shared中增加自定义的SignedStorageAsk类型
本PR: 为 filecoin-project/venus/issues/5263 的子任务
前置任务: https://github.com/filecoin-project/venus/pull/5280
=> feat: using SignedStorageAsk defined in `venus-shared` instead of  in `go-fil-market`/使用`venus-shared`中定义的SignedStorageAsk替换`go-fil-market`中的定义.

go.mod, go.sum
=> chore: upgrade venus package of go mod/升级venus的go mod 依赖.

cli/stats.go, cmd/venus-market/main.go
close https://github.com/filecoin-project/venus/issues/5160
=> feat: add cli to stats deal

cmd/market-client/storage.go, dagstore/wrapper.go, dagstore/wrapper_test.go
close https://github.com/filecoin-project/venus/issues/5311
lotus pr：https://github.com/filecoin-project/lotus/pull/9010 https://github.com/filecoin-project/lotus/pull/8896 
=> feat: dagstore: Add DestroyShard() in dagstore wrapper

cli/util.go, cmd/market-client/main.go, cmd/market-client/paych.go
resolve filecoin-project/venus#4907
=> feat: 增加paych相关命令

models/badger/paych.go, models/badger/testing.go, models/testhelpers.go
当前`repo.PaychChannelInfoRepo`和`repo.PaychMsgInfoRepo`两个接口都由`paychRepo`实现, 他们底层的badger ds共享相同的`namespace`: 'paych'.
然后根据具体的业务, 在业务中动态添加上子的`namespace`.
此提交将`paychRepo`拆分成两个独立的`namespace`封装的独立类型.
目的是支持: 
[bader数据在不同版本之间的自动迁移的框架的实现](https://github.com/filecoin-project/venus/issues/5283)
当前的问题是, 在自动迁移时, 由于在底层没有把'namesapce'区分, 迁移框架只能从`paych`的`namespace`开始遍历, 导致在迁移时数据处于混乱状态.
在迁移完成后, 迁移框架会自动在`namespace`中间添加版本号.
例如: 
`/paych/ChannelInfo` -> `paych/1/ChannelInfo`
如果在迁移时自己加上子namespace, 就会变成:
`/paych/ChannelInfo` -> `paych/ChannelInfo/1/`, 但是在具体的业务中, 又指定了`ChannelInfo/xxxx`, 
所以, 在迁移之前动态添加子空间是行不通的.
如果进行拆分, 以`repo.PaychChannelInfoRepo`为例:
其默认的namespace就是`/paych/ChannelInfo`, 完成后, 变成`/paych/ChannelInfo/1/...`,
而业务中, 也不会在查询时同态的添加`namespace`, 所以, 不会有任何问题.
在你认为本 PR 满足被审阅的标准之前，需要确保 / Before you mark the PR …
=> refactor: 解耦 payChInfoRepo 和 payMsgRepo

models/badger/migrate/migrate.go
close nil
fix: migrate market client panic
=> fix: market client crush caused by migrate a nil ds/market-client迁移了空的ds导致panic.

storageprovider/deal_tracker.go
close https://github.com/filecoin-project/venus/issues/5447
=> feat: add deal expired check

cmd/venus-market/run.go, go.mod, go.sum
ref https://github.com/filecoin-project/venus/issues/4870
=> feat: update the authClient with token

dagstore/market_api.go, dagstore/market_api_test.go, dagstore/modules.go, go.mod, go.sum, piecestorage/filestore.go, piecestorage/memstore.go, piecestorage/s3.go, piecestorage/storagemgr.go, piecestorage/type.go
close filecoin-project/venus#5484
=> feat: unsealed from sp through venus-gateway / 通过venus-gateway给SP下发unsealed请求

api/impl/venus_market.go, go.mod, go.sum, storageprovider/deal_assigner.go
close https://github.com/filecoin-project/venus/issues/5853
新增 ReleaseDeals 接口，用于释放通过 AssignUnPackedDeals 接口分配的订单
=> feat: new api ReleaseDeals

cli/storage-deals.go, cli/util.go, client/client_test.go, client/import.go, client/import_test.go, config/save.go, dagstore/mount_test.go, piecestorage/filestore.go, piecestorage/memstore.go, rpc/piece_storage_server_test.go, rpc/rpc.go, utils/algn_zero_reader_test.go
=> chore: Remove dependency on io/ioutil package

.gitignore, Makefile, dagstore/mongo_topindex.go, dagstore/mongo_topindex_test.go, models/badger/shard.go, models/mysql/shard.go, models/repo/repo.go, tools/index/README.md, tools/index/main.go
close https://github.com/ipfs-force-community/droplet/issues/343
=> feat: tools: generate car index and import index to mongo

go.mod, go.sum, models/badger/storage_deal_test.go
close https://github.com/ipfs-force-community/droplet/issues/373
=> fix: memory leak

docs/zh/droplet-client配置解释.md, docs/zh/droplet配置解释.md, docs/zh/快速启用.md
=> update deploy docs / 更新部署文档

cli/retrieval-deals.go, retrievalprovider/datatransfer_handler.go
close https://github.com/ipfs-force-community/droplet/issues/384
=> fix: not set retrieval deal status

api/impl/venus_market.go, go.mod, go.sum, storageprovider/deal_assign_util.go, storageprovider/deal_assign_util_test.go, storageprovider/deal_assigner.go
close
支持根据 SectorExpiration 过滤 deals
=> feat: support filter deals by SectorExpiration

cmd/droplet/run.go, retrievalprovider/httpretrieval/server.go, retrievalprovider/httpretrieval/server_test.go
close https://github.com/ipfs-force-community/droplet/issues/400
=> fix: Use the unified piecestorage object

dagstore/wrapper.go
=> fix: remove trace goroutine for dagstore wrapper

storageprovider/ondealsectorcommitted.go
lotus pr: https://github.com/filecoin-project/lotus/pull/11215/files#diff-57e41e1310e0507239e07304b04d39bd28567e2282dacf0343355d5e27432f70
=> feat: handle PreCommitSectorBatch2 message

docs/zh/快速启用.md
=> docs: update quick start doc

cmd/droplet-client/main.go, cmd/droplet-client/pieceinfo.go, cmd/droplet-client/util.go
close https://github.com/ipfs-force-community/droplet/issues/432
=> feat: generate manifest by piece file

client/client.go, cmd/droplet-client/data.go, utils/commp.go
close https://github.com/ipfs-force-community/droplet/issues/393
=> opt: support offline compute commp

cmd/droplet/run.go, models/badger/storage_deal.go, models/badger/storage_deal_test.go, models/mysql/storage_deal.go, models/mysql/storage_deal_test.go, retrievalprovider/httpretrieval/server.go, retrievalprovider/httpretrieval/server_test.go
=> feat: filter retrieval by deal piece

piecestorage/storagemgr.go, piecestorage/storagemgr_test.go, piecestorage/store_wrapper.go
close https://github.com/ipfs-force-community/droplet/issues/437
=> opt: piece storage supports files with .car suffix

docs/zh/快速启用.md
=> fix docs droplet actor-funds add command

api/impl/venus_market.go, cli/storage-deals.go, go.mod, go.sum, storageprovider/storage_provider.go
close https://github.com/ipfs-force-community/droplet/issues/462
=> feat: import data by uuid

cli/storage-deals.go, storageprovider/stream.go
fix: use the received deal uuid
close
=> chore: cherry pick 472

client/client.go
close https://github.com/ipfs-force-community/droplet/issues/475
=> fix: peer id is nil

retrievalprovider/datatransfer_handler.go, retrievalprovider/provider_datatransfer_sub.go
fix: https://github.com/ipfs-force-community/droplet/pull/477
在 447 中的修复会导致检索卡住（设置了检索价格）
=> fix: Paid retrieval failed

retrievalprovider/httpretrieval/multi_reader.go, retrievalprovider/httpretrieval/multi_reader_test.go, retrievalprovider/httpretrieval/server.go, retrievalprovider/httpretrieval/server_test.go
close https://github.com/ipfs-force-community/droplet/issues/360
=> feat: retrieval padding piece

docs/en/getting-started.md, docs/zh/快速启用.md
=> chore: update doc about retrieval

piecestorage/filestore.go, piecestorage/filestore_test.go
close https://github.com/ipfs-force-community/droplet/issues/464
=> feat: piecestorage support recursive lookup file

piecestorage/filestore_test.go
测试 piecestorage 存在大量文件时查找文件的耗时。
```
file name tmp_0_1103 took 1.660636479s
file name 3_555 took 112.515107ms
file name tmp_6_2760 took 1.614398641s
file name 9_369 took 256.373337ms
file name tmp_12_1706 took 1.624127085s
file name 15_369 took 46.811549ms
```
=> test: Querying files from a large number of files takes time

storageprovider/deal_assign_util.go, storageprovider/deal_assigner.go
=> fix: assign direct deal

api/impl/venus_market.go, cli/direct-deal.go, cmd/droplet-client/direct-deal.go, cmd/droplet-client/retrieval.go, cmd/droplet-client/storage_v2.go, go.mod, go.sum
=> feat: add cli to update direct deal state

storageprovider/deal_assigner.go
=> fix: reduce log output

retrievalprovider/transports.go
If announce addresses are configured, the retrieval provider now prioritizes these over the addresses directly obtained from the host. This allows fora more controlled announcement of addresses in libp2p networks.
close
=> feat(retrievalprovider): prioritize announce addresses over host addresses

go.mod, go.sum, version/version.go
=> chore: bump version to v2.12.0

docs/zh/spark.md
=> doc: add spark doc

tools/index/README.md, tools/index/main.go
=> opt: support generate direct deal index

cmd/droplet-client/direct-deal.go
=> feat: generate deal info from message

go.mod, go.sum, storageprovider/deal_handler.go, storageprovider/storage_provider.go
=> fix: Separate coroutine generation index
